"""Songs database."""


class LandcoreSongs:
    """Provides info for all landcore songs."""

    URLS = [
        "https://youtu.be/AWp0I7bYAyM",
        "https://youtu.be/S82NBonU164",
        "https://youtu.be/p9XTc6MrhNM",
        "https://youtu.be/IGM_Z5978ok",
        "https://youtu.be/fdW2VgAO4Us",
        "https://youtu.be/FCX2-m9LK5c",
        "https://youtu.be/iZ9J6LdLZGc",
        "https://youtu.be/eNnLYPTz1-I",
        "https://youtu.be/_mOywGAZyWs",
        "https://youtu.be/WbUwkx3v9OA",
        "https://youtu.be/vfu7k3KylRs",
        "https://youtu.be/97V71XHUsvo",
        "https://youtu.be/GhGd2tVAIVs",
        "https://youtu.be/y6SWP8iY_wk",
        "https://youtu.be/li-2tDxhaDM",
        "https://youtu.be/iMKa1ZOU5Yk",
        "https://youtu.be/K9-ShHycqdg",
        "https://youtu.be/CGGiXnKPs3g",
        "https://youtu.be/ms0WJnO9rMU",
        "https://youtu.be/shpT7JuqnXE",
        "https://youtu.be/I8xqcsVl9yE",
        "https://youtu.be/fpeHMRj0q8U",
        "https://youtu.be/kOYDN0xPUjY",
        "https://youtu.be/L5kv8XsKRPI",
        "https://youtu.be/46MjpOqO5lQ",
        "https://youtu.be/wz1nnmraa0c",
        "https://youtu.be/_97Ak-yX854",
        "https://youtu.be/onbLVlJXqg0",
        "https://youtu.be/ES1x752QehI",
        "https://youtu.be/B7-XRUhbULY",
        "https://youtu.be/fGDdHM_mPGg",
        "https://youtu.be/fvPGSUrnPWY",
        "https://youtu.be/d4mDfdhElv0",
        "https://youtu.be/YRlB6sDfGA4",
        "https://youtu.be/ien7A9viCvo",
        "https://youtu.be/JCLu7LCwZD0",
        "https://youtu.be/l-Qwmjlkcw0",
        "https://youtu.be/XALy-TbJeFM",
        "https://youtu.be/RuAIgPQ8Zcw",
        "https://youtu.be/r-avmdM1KEQ",
        "https://youtu.be/_qfmUS_gXts",
        "https://youtu.be/5QsLDlqAvoQ",
        "https://youtu.be/s8SNfmbt3FM",
        "https://youtu.be/ZPGjvQRhLQI",
        "https://youtu.be/2C6qTmFJ3zU",
        "https://youtu.be/LcOPYItBsSM",
        "https://youtu.be/os03GTmhGIE",
        "https://youtu.be/vIus11ezA8E",
        "https://youtu.be/5W3U6bCF_Zc",
        "https://youtu.be/H-C3bnnoYQw",
        "https://youtu.be/_mcJPtib08M",
        "https://youtu.be/7rPnVJggIdY",
        "https://youtu.be/U24yn3nlH64",
        "https://youtu.be/aCcDH-TvBI8",
        "https://youtu.be/TUMnDEje4kI",
        "https://youtu.be/VMCSyRHX3cQ",
        "https://youtu.be/oaomY92HMc4",
        "https://youtu.be/JgVDjKHFJko",
        "https://youtu.be/9PNI4IOmYE8",
        "https://youtu.be/h-c5FzvkQXE",
        "https://youtu.be/c6zJuDYOtv0",
    ]

    NAMES = [
        ("nay-golemiya", "pecata"),
        ("pesho baftata ringtone", "ringtone", "baftata ringtone", "ringtone baftata"),
        ("pesho baftata", "baftata", "pesho", "pe6o", "bafta"),
        ("paulo coelho", "paulo", "koelyo", "koelyu", "paulu"),
        ("landcore classic", "classic 1", "landkor klasik", "classic", "klasik"),
        ("com.sap.geekyMazenRap.wav", "stoyo velev", "neno pie bira", "maikati", "maykati"),
        ("kris da silent", "kris", "chris"),
        ("yanko vodata", "vodata", "yanko", "paynera", "qnko vodata", "qnko"),
        ("pohuai",),
        ("devkata le6", "devkata lesh", "devkata", "le6", "lesh", "devor"),
        ("imahme nie", "boeva", "imame nie"),
        ("ayde 5", "filcho", "filip", "5", "ayde pet", "aide 5"),
        ("pesho baftata remastered",),
        ("pesho baftata pleasure live", "live s pleasure", "baftata live", "pesho baftata live", "live"),
        ("ehee", "exee", "ehe", "exe", "landkora", "nyamame umora"),
        ("pesho baftata rerecorded",),
        ("sandyokanka",),
        ("mozhe bi imahte predvid", "naftata", "pesho naftata", "aftata"),
        ("6 bez 5", "richito", "6 bez 10", "shest bez pet"),
        ("under p360", "andar", "pesho", "under", "p360", "pe6o"),
        ("nenny b", "neni b", "nenko"),
        ("satoshi", "bitcoin", "bitcoina", "bitkoyn", "bitkoyna"),
        ("landcore classic 2", "classic 2", "landkor klasik 2", "classic", "klasik 2", "klasik"),
        ("communication romanation", "kamyunikeyshan rumaneyshan", "albena"),
        ("6aka", "shestaka", "i sere paveta" "6", "shest", "6ака"),
        ("devastation", "devasteyshan"),
        ("fmi", "algebra"),
        ("hex", "heks", "keks"),
        ("opa", "da si go pompi"),
        ("dis", "analiz", "proizvodni", "kolega", "ne me zanimavai", "analiza"),
        ("hadzhi ignatov", "darvenitsa", "ignatov", "haji ignatov"),
        ("shefa na bloka 2", "yuli"),
        ("094", "94", "devet chetiri", "tova e avtobusa"),
        ("411", "na uspeha chisloto", "maionezata"),
        ("325", "plank", "musakata"),
        ("paulo coelho live", "live s baftata", "live"),
        ("pesho baftata live", "live s baftata", "baftata s baftata", "baftata live", "live", "live s pesho baftata"),
        ("210", "zalata golyama", "210 brat", "zalata golqma", "bam bam"),
        ("stupid horse", "konferansa", "kon"),
        ("landcore classic 3", "classic 3", "landkor klasik 3", "classic", "klasik 3", "klasik"),
        ("garageband", "garage band", "landcore mashinata", "landkor mashinata"),
        ("attaxic",),
        ("slack mozhe bi", "swag moje bi", "chernite ninji", "nindzhi", "slak"),
        ("landcore avantgarde", "landkor avangard"),
        ("i pochvam da kodya bate", "pisha koda i si hoda", "pochvam da kodya", "pochvam da kodq"),
        ("opkphdvmptv", "moi angele", "sasho roman", "perspektiva", "sars"),
        ("ivan", "ivan an", "motora", "baron purple", "rasista"),
        ("fizichen landcore", "fizichen landkor", "fizikata", "sastezanieto", "fizichen"),
        ("peshets", "tu varna", "piene"),
        ("lev i pedese", "1.50", "stola", "chetvorkata"),
        ("skate parka", "skeyt parka", "skeit parka", "skate", "skeyt"),
        ("stack overflow", "push", "pop", "po tsyal den samo", "po cql den samo"),
        ("the le6 element", "vitas", "7th element", "le6 element"),
        ("schupenoto", "s4upenoto", "na baftata", "29/8?", "29/8"),
        ("spokoino", "spokoino kolega", "statistika", "statistikata"),
        ("chumata", "4umata", "chuma", "4uma"),
        ("nasko nasko", "bat nasko", "bat nasko nasko", "nasko"),
        ("shema // praim", "shema praim", "shema prajm", "shema", "shemata", "keshovartezh"),
        ("100qn", "stoyan", "stoqn", "child in time"),
        ("landcore classic 4", "classic 4", "landkor klasik 4", "classic", "klasik 4", "klasik"),
        ("retrospekt", "darzhavniya", "retrospektsiya", "retrospekciq"),
    ]

    QUOTES = [
        "пешо нешо",
        "бафтата бафтата",
        "денем стиска ти здраво ръката",
        "нощем ле6ира се на звездата",
        "пумняняня конняняня пуманяняняня гиш",
        "пецата пецата пецата пецата а ъ",
        "фул дроп до гроб",
        "два стека бира",
        "раз, два, три и започва сеира",
        "6\n6\n6ака",
        "шест крака",
        "Issere Pavetta.",
        "полива си цветята с минерална вода",
        "желирани мечета",
        "maikati maikati maikati maikati maaa",
        "гамата гамата гамата гамата маз-на",
        "мазната мазната мазната мазната га-ма",
        "защото в кода ползвах hex",
        "да си го помпи, който си иска",
        "само бобена чорба.",
        "то се видя...",
        "кон",
        "слон",
        "хахаа",
        "hahaa",
        "маацки му намигат",
        "крис не се чува",
        "люс люс",
        "малко пичбенд да сложим",
        "> Ама аз не са чувам\n- JJ",
        "може би имахте предвид Пешо Нафтата",
        "раз, два, три, четири.\n||пет.||",
        "Алхимикът",
        "> Цитати, дебати, животът ти разказвам.\n- П. К.",
        "> Как да си живееш живота ти показвам.\n- П. К.",
        "с. Дългопросен",
        "икуменстрал",
        "24/8",
        "една храна ако може",
        "бирен фъстък за два лева",
        "шшшш тихо",
        "слагай си крилата че потопа ща излапа",
        "Bloodvastation",
        "момчета ай едно инструменталче",
        "5ца песен",
        "коня оня",
        "очилата ата",
        "бобът се накисва във студена вода",
        "666ака",
        "лев и педесе",
        "под бора",
        "чек че почва бийта брат",
        "не бе брат, това е друга песен",
    ]
